import report from '@/data/report.json';

import { LivePanel } from './LivePanel';
import type { PanelReport } from './PanelView';

/**
 * The demo panel.
 *
 * Server-renders a report captured from the real tool, then hands over to `LivePanel`,
 * which re-takes it against this page's own forked button once the client bundle has
 * loaded. Two consequences worth stating: the panel is never blank while it waits, and
 * if the client never arrives the captured report is what stays.
 *
 * `src/data/report.json` is not hand-typed either — it is generated by `?xray-dump=` in
 * the playground (see the site README), so "real output" is a claim you can re-check
 * rather than one you have to take on trust.
 */
export function Panel() {
  return <LivePanel initial={report as PanelReport} />;
}
